name: CI/CD Workflow for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-Subscription-Service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
          unzip gradle-7.5-bin.zip
          sudo mv gradle-7.5 /opt/gradle
          sudo ln -s /opt/gradle/bin/gradle /usr/local/bin/gradle

      - name: Grant execute permissions
        run: chmod +x ./gradlew

      - name: Build Subscription-Service
        working-directory: ./Subscription-Service
        run: ./gradlew build

      - name: Run Subscription-Service Tests
        working-directory: ./Subscription-Service
        run: ./gradlew test

      - name: Run Subscription-Service with Secrets
        working-directory: ./Subscription-Service
        env:
          URL: ${{ secrets.URL_DB }}
          USERNAME: ${{ secrets.USER_NAME_DB }}
          PASSWORD: ${{ secrets.PASSWORD_DB }}
        run: ./gradlew run

  build-Notification-Service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.5-bin.zip
          unzip gradle-7.5-bin.zip
          sudo mv gradle-7.5 /opt/gradle
          sudo ln -s /opt/gradle/bin/gradle /usr/local/bin/gradle

      - name: Grant execute permissions
        run: chmod +x ./gradlew

      - name: Build Notification-Service
        working-directory: ./Notification-Service
        run: ./gradlew build

      - name: Run Notification-Service Tests
        working-directory: ./Notification-Service
        run: ./gradlew test

      - name: Run Notification-Service with Secrets
        working-directory: ./Notification-Service
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTHTOKEN: ${{ secrets.TWILIO_AUTHTOKEN }}
          TWILIO_PHONENUMBER: ${{ secrets.TWILIO_PHONENUMBER }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          USERNAME: ${{ secrets.USERNAME }}
        run: ./gradlew run
