name: CI/CD Workflow for Microservices

# Evento que dispara el workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Configuración de jobs para cada microservicio
jobs:
  build-service1:
    runs-on: ubuntu-latest

    steps:
      # Clona el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Configura la versión de Java (ajusta según tu versión de Java)
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Compila y prueba el primer microservicio
      - name: Build Service 1
        working-directory: ./service1
        run: ./gradlew build

      - name: Run Service 1 Tests
        working-directory: ./service1
        run: ./gradlew test

  build-service2:
    runs-on: ubuntu-latest

    steps:
      # Clona el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Configura la versión de Java
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Compila y prueba el segundo microservicio
      - name: Build Service 2
        working-directory: ./service2
        run: ./gradlew build

      - name: Run Service 2 Tests
        working-directory: ./service2
        run: ./gradlew test
