name: CI/CD Workflow for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-service1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build Service 1
        working-directory: ./service1
        run: ./gradlew build

      - name: Run Service 1 Tests
        working-directory: ./service1
        run: ./gradlew test

  build-service2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build Service 2
        working-directory: ./service2
        run: ./gradlew build

      - name: Run Service 2 Tests
        working-directory: ./service2
        run: ./gradlew test
